# Generated by Django 5.2.4 on 2025-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_societysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='societysubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
