# Generated by Django 5.2.4 on 2025-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_societysubmission_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='society',
            field=models.CharField(choices=[('experimental_theatre_lab', 'Experimental Theatre Lab'), ('metropolitan_drama', 'Metropolitan Drama Society'), ('riverside_players', 'Riverside Players')], default='experimental_theatre_lab', max_length=50),
        ),
    ]
