# Generated by Django 5.2.4 on 2025-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_event_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='society',
            field=models.CharField(choices=[('experimental_theatre_lab', 'Experimental Theatre Lab'), ('metropolitan_drama', 'Metropolitan Drama Society'), ('riverside_players', 'Riverside Players'), ('cats_theatre', 'C.A.T.S. Theatre')], default='experimental_theatre_lab', max_length=50),
        ),
    ]
